"""add todo table

Revision ID: 656e595e631a
Revises: 691bb3ebe976
Create Date: 2020-04-08 15:08:06.261519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656e595e631a'
down_revision = '691bb3ebe976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_content'), 'todos', ['content'], unique=False)
    op.create_index(op.f('ix_todos_name'), 'todos', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_name'), table_name='todos')
    op.drop_index(op.f('ix_todos_content'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
