"""empty message

Revision ID: 691bb3ebe976
Revises: 66f4a42f818d
Create Date: 2020-04-07 11:19:26.874807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691bb3ebe976'
down_revision = '66f4a42f818d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('birth', sa.String(length=10), nullable=True))
    op.add_column('user_info', sa.Column('sex', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_info_birth'), 'user_info', ['birth'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_birth'), table_name='user_info')
    op.drop_column('user_info', 'sex')
    op.drop_column('user_info', 'birth')
    # ### end Alembic commands ###
